<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

        <xacro:include filename="$(find talos_description)/urdf/wheel/back_wheel.urdf.xacro" />
	<xacro:include filename="$(find talos_description)/urdf/wheel/caster_wheel.urdf.xacro" />
        <xacro:include filename="$(find talos_description)/urdf/wheel/back_wheel.transmission.xacro" /> 
        <xacro:include filename="$(find talos_description)/urdf/wheel/caster_wheel.transmission.xacro" /> 

	<xacro:property name="base_width" value="0.62265" />
	<xacro:property name="base_height" value="0.37817" />
	<xacro:property name="base_skirt_height_guestimate" value="0.073" />
	<xacro:property name="base_mass" value="8.20" />
	<xacro:property name="caster_to_side_offset" value="0.2175" />
	<xacro:property name="caster_to_front_offset" value="0.21745" />
	<xacro:property name="back_wheel_to_side_offset" value="0.229125" />
	<xacro:property name="back_wheel_to_back_offset" value="0.2" />
	<xacro:property name="back_wheel_vertical_offset" value="0.040132" />

	<xacro:macro name="base" params="name">
	
		<link name="${name}_link">
		  <visual>
			<geometry>
			  <mesh filename="package://talos_description/meshes/base/base_link.stl" scale="${scale} ${scale} ${scale}"/>
			</geometry>
			<material name="white"/>
		  </visual>
		  <collision>
			<origin xyz="0 0 ${base_height/2 - base_skirt_height_guestimate}" rpy="0 0 0"/>
			<geometry>
			  <box size="${base_width} ${base_width} ${base_height}" />
			</geometry>
		  </collision>
		  <xacro:inertial_template mass="${base_mass}" length="${base_width}" width="${base_width}" height="${base_height}"/>
		</link>

                <xacro:caster_wheel prefix="fl" parent="base_link">
                    <origin xyz="${caster_to_side_offset} ${caster_to_front_offset} 0" rpy="0 0 0"/>
                </xacro:caster_wheel>    

                <xacro:caster_wheel prefix="fr" parent="base_link">
                    <origin xyz="${-caster_to_side_offset} ${caster_to_front_offset} 0" rpy="0 0 0"/>
                </xacro:caster_wheel>

                <xacro:back_wheel prefix="bl" parent="base_link">
                    <origin xyz="${back_wheel_to_side_offset} ${-back_wheel_to_back_offset} -${back_wheel_vertical_offset}" rpy="0 0 0"/>
                </xacro:back_wheel>   

                <xacro:back_wheel prefix="br" parent="base_link">
                   <origin xyz="${-back_wheel_to_side_offset} ${-back_wheel_to_back_offset} -${back_wheel_vertical_offset}" rpy="0 0 0"/>
                </xacro:back_wheel>   

		<xacro:caster_wheel_transmission prefix="fl"/>
		<xacro:caster_wheel_transmission prefix="fr"/>
		<xacro:back_wheel_transmission prefix="br"/>
                <xacro:back_wheel_transmission prefix="bl"/>
	</xacro:macro>

</robot>
